### ISSUE TITLE
Slight format change request

### ISSUE THREAD

**Issue by stevenweaver** [veg/alignment.js#17]
Would it be possible to add a new key, `sequences`, that holds the array of sequences and their respective headers? This way, metadata such as `number_of_sequences` and `number_of_sites` won't need to be filtered when traversing.

**Comment by stephenshank** [comment]
It would be possible, but this appears to require either a breaking change or some redundancy.

> This way, metadata such as number_of_sequences and number_of_sites won't need to be filtered when traversing.

The current `fastaParser` implementation returns an array, with a few key/value pairs populated (arrays are objects). Despite adding such metadata, it works nicely with both `forEach`, `map`, `sort`, and others. Iteration occurs over all records (and only these records) using native JavaScript, and not requiring a filter.

However, I see that it does not work as nicely with `_.values`, and these two metadata show up. This feels like an edge case to me. Why call `_.values` to begin with? I suspect all `Array` methods work as expected.
